//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreBookOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatHang
    {
        public int MaDDH { get; set; }
        public int MaKH { get; set; }
        public int MaSach { get; set; }
        public Nullable<int> KhachHang_MaKhach { get; set; }
        public Nullable<int> HoaDon_MaHD { get; set; }
        public Nullable<int> KhachHang_MaKhach1 { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Sach Sach { get; set; }
        public virtual KhachHang KhachHang1 { get; set; }
    }
}
