//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreBookOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.DonDatHangs = new HashSet<DonDatHang>();
            this.GioHangs = new HashSet<GioHang>();
            this.NCC_Sach = new HashSet<NCC_Sach>();
        }
    
        public int MaSach { get; set; }
        public string TenSach { get; set; }
        public string Anh { get; set; }
        public string TacGia { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<float> DonGia { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<int> TheLoaiSach_MaLoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonDatHang> DonDatHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NCC_Sach> NCC_Sach { get; set; }
        public virtual TheLoaiSach TheLoaiSach { get; set; }
    }
}
